spring.data.mongodb.uri=mongodb+srv://AWS:RedAcademica2026@redacademica.etsrlhc.mongodb.net/redacademicauq?retryWrites=true&w=majority&appName=RedAcademica
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Optional email settings for password recovery
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=redacademicauq@gmail.com
spring.mail.password=odmlhaommsjuefnb
spring.mail.from=redacademicauq@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true